CREATE DATABASE OperationDB

CREATE SCHEMA [HH]

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[HH].[Operation]') AND type in (N'U'))
BEGIN
CREATE TABLE [HH].[Operation](
	[Id] int IDENTITY(1,1) NOT NULL,	
	[Code] VARCHAR(250) NOT NULL,
    [Name] VARCHAR(250) NOT NULL 
CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END