
@hostname=localhost
@port=7056

GET https://{{hostname}}:{{port}}/Operation
###
GET https://{{hostname}}:{{port}}/Operation/allWithAtrributes
###
@code= xd94
@name = fdg
POST https://{{hostname}}:{{port}}/Operation
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{ 
  "Code":"{{code}}",
  "Name":"{{name}}"
}
###

POST https://{{hostname}}:{{port}}/Operation/attribute
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{ 
  "createOperationDTO":{
  "Code":"{{code}}",
  "Name":"{{name}}"
  },
  "attributes":
  {
  "id":"1068",
  "code":"xd",
  "test":"tes334",
  "afsdfd1":"adasd3"
  }
}
###
DELETE https://{{hostname}}:{{port}}/Operation?code={{code}}

###
DELETE https://{{hostname}}:{{port}}/Operation/all

###
#cosmos DB

POST https://{{hostname}}:{{port}}/OperationAttribute 
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "id":"1068",
  "code":"xd",
  "test":"tes334",
  "afsdfd1":"adasd3"
}
###
GET https://{{hostname}}:{{port}}/OperationAttribute
###