
@hostname=localhost
@port=7056

@id= 11
@code= xd944
@name = fdg


GET https://{{hostname}}:{{port}}/Operation
###

GET https://{{hostname}}:{{port}}/Operation/operations
###

GET https://{{hostname}}:{{port}}/Operation/attributes
###

GET https://{{hostname}}:{{port}}/Operation/operations/id/{{id}}
###

GET https://{{hostname}}:{{port}}/Operation/operations/code/{{code}}
###


GET https://{{hostname}}:{{port}}/Operation/attributes/id/{{id}}
###

GET https://{{hostname}}:{{port}}/Operation/attributes/code/{{code}}
###

GET https://{{hostname}}:{{port}}/Operation/id/{{id}}
###

GET https://{{hostname}}:{{port}}/Operation/code/{{code}}
###

POST https://{{hostname}}:{{port}}/Operation/operations
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{ 
  "Code":"{{code}}",
  "Name":"{{name}}"
}
###

POST https://{{hostname}}:{{port}}/Operation/attributes
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

  {
  "id":"{{id}}",
  "code":"{{code}}",
  "test":"tes334",
  "afsdfd1":"adasd3"
  }
###

POST https://{{hostname}}:{{port}}/Operation
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{ 
  "createOperationDTO":{
  "Code":"{{code}}",
  "Name":"{{name}}"
  },
  "attributes":
   {
  "id":"{{id}}",
  "code":"{{code}}",
  "test":"tes334",
  "afsdfd1":"adasd3"
  }
} 
###

DELETE https://{{hostname}}:{{port}}/Operation/id/{{id}}
###

DELETE https://{{hostname}}:{{port}}/Operation/code/{{code}}
###

DELETE https://{{hostname}}:{{port}}/Operation/attributes/id/{{id}}
###

DELETE https://{{hostname}}:{{port}}/Operation/attributes/code/{{code}}
###

DELETE https://{{hostname}}:{{port}}/Operation
###

DELETE https://{{hostname}}:{{port}}/Operation/cache
###




