--CREATE DATABASE OperationDB

--CREATE SCHEMA [HH]


CREATE TABLE [HH].[Operation](
	[Id] int IDENTITY(1,1) NOT NULL,	
	[Code] VARCHAR(250) NOT NULL,
    [Name] VARCHAR(250) NOT NULL 
CONSTRAINT [PK_Operation] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


GO

CREATE TABLE [HH].[OperationPlanned](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OperationId] [int] NOT NULL,	
	[StartDate] DATETIME2 NOT NULL,
	[EndDate] DATETIME2 NOT NULL,
 CONSTRAINT [PK_OperationPlanned] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [HH].[OperationStarted](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OperationPlannedId] [int] NOT NULL,	
	[StartDate] DATETIME2 NOT NULL	
 CONSTRAINT [PK_OperationStarted] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [HH].[OperationPlanned]
ADD CONSTRAINT FK_OperationPlanned_Operation FOREIGN KEY (OperationId) REFERENCES [HH].[Operation] (Id);

ALTER TABLE [HH].[OperationStarted]
ADD CONSTRAINT FK_OperationStarted_Operation FOREIGN KEY (OperationPlannedId) REFERENCES [HH].[OperationPlanned] (Id);